services:
  base: &base
    image: chatwoot/chatwoot:v3.16.0  # Usar imagen oficial en lugar de build
    tty: true
    stdin_open: true
    env_file: .env

  rails:
    <<: *base
    volumes:
      - ./:/app/local_code:delegated  # Tu código estará en /app/local_code
      - packs:/app/public/packs
      - cache:/app/tmp/cache
    depends_on:
      - postgres
      - redis
      - mailhog
      - sidekiq
    ports:
      - 3001:3000
    env_file: .env
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    volumes:
      - ./:/app/local_code:delegated
      - packs:/app/public/packs
      - cache:/app/tmp/cache
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot123

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres:
  redis:
  packs:
  cache: